name: Apply Prettier Formatting
on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
    paths:
    - 'src/**'
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v5
      with:
        submodules: 'true'
    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: '24'
        cache: 'yarn'
    - name: Install dependencies and format
      run: |
        yarn
        yarn format
    - name: Apply fixes
      uses: ./.github/actions/autofix-ci
      with:
        commit-message: "auto: Apply Prettier format"